package com.bbgu.zmz.community.mapper;

import com.bbgu.zmz.community.model.Commentagree;
import com.bbgu.zmz.community.model.CommentagreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentagreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    long countByExample(CommentagreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int deleteByExample(CommentagreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int insert(Commentagree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int insertSelective(Commentagree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    List<Commentagree> selectByExampleWithRowbounds(CommentagreeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    List<Commentagree> selectByExample(CommentagreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    Commentagree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Commentagree record, @Param("example") CommentagreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Commentagree record, @Param("example") CommentagreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Commentagree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentagree
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(Commentagree record);
}