package com.bbgu.zmz.community.mapper;

import com.bbgu.zmz.community.model.Kind;
import com.bbgu.zmz.community.model.KindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    long countByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int deleteByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int insert(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int insertSelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    List<Kind> selectByExampleWithRowbounds(KindExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    List<Kind> selectByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    Kind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(Kind record);
}