package com.bbgu.zmz.community.mapper;

import com.bbgu.zmz.community.model.Topicinfo;
import com.bbgu.zmz.community.model.TopicinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TopicinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    long countByExample(TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int deleteByExample(TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int insert(Topicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int insertSelective(Topicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    List<Topicinfo> selectByExampleWithBLOBsWithRowbounds(TopicinfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    List<Topicinfo> selectByExampleWithBLOBs(TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    List<Topicinfo> selectByExampleWithRowbounds(TopicinfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    List<Topicinfo> selectByExample(TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    Topicinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Topicinfo record, @Param("example") TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Topicinfo record, @Param("example") TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Topicinfo record, @Param("example") TopicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Topicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByPrimaryKeyWithBLOBs(Topicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicinfo
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    int updateByPrimaryKey(Topicinfo record);
}