package com.bbgu.zmz.community.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.catename
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private String catename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long categoryCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long categoryModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.catename
     *
     * @return the value of category.catename
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public String getCatename() {
        return catename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.catename
     *
     * @param catename the value for category.catename
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCatename(String catename) {
        this.catename = catename == null ? null : catename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_create
     *
     * @return the value of category.category_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCategoryCreate() {
        return categoryCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_create
     *
     * @param categoryCreate the value for category.category_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCategoryCreate(Long categoryCreate) {
        this.categoryCreate = categoryCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_modified
     *
     * @return the value of category.category_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCategoryModified() {
        return categoryModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_modified
     *
     * @param categoryModified the value for category.category_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCategoryModified(Long categoryModified) {
        this.categoryModified = categoryModified;
    }
}