package com.bbgu.zmz.community.model;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.topic_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long collectCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long collectModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.topic_id
     *
     * @return the value of collect.topic_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.topic_id
     *
     * @param topicId the value for collect.topic_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_create
     *
     * @return the value of collect.collect_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getCollectCreate() {
        return collectCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_create
     *
     * @param collectCreate the value for collect.collect_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setCollectCreate(Long collectCreate) {
        this.collectCreate = collectCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_modified
     *
     * @return the value of collect.collect_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getCollectModified() {
        return collectModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_modified
     *
     * @param collectModified the value for collect.collect_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setCollectModified(Long collectModified) {
        this.collectModified = collectModified;
    }
}