package com.bbgu.zmz.community.model;

public class Commentagree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentagree.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentagree.userid
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentagree.comment_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentagree.id
     *
     * @return the value of commentagree.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentagree.id
     *
     * @param id the value for commentagree.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentagree.userid
     *
     * @return the value of commentagree.userid
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentagree.userid
     *
     * @param userid the value for commentagree.userid
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentagree.comment_id
     *
     * @return the value of commentagree.comment_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentagree.comment_id
     *
     * @param commentId the value for commentagree.comment_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
}