package com.bbgu.zmz.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.topic_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long commentCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long commentModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.agree_num
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long agreeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_accept
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Integer isAccept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.topic_id
     *
     * @return the value of comment.topic_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.topic_id
     *
     * @param topicId the value for comment.topic_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_create
     *
     * @return the value of comment.comment_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCommentCreate() {
        return commentCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_create
     *
     * @param commentCreate the value for comment.comment_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCommentCreate(Long commentCreate) {
        this.commentCreate = commentCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_modified
     *
     * @return the value of comment.comment_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCommentModified() {
        return commentModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_modified
     *
     * @param commentModified the value for comment.comment_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCommentModified(Long commentModified) {
        this.commentModified = commentModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.agree_num
     *
     * @return the value of comment.agree_num
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getAgreeNum() {
        return agreeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.agree_num
     *
     * @param agreeNum the value for comment.agree_num
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setAgreeNum(Long agreeNum) {
        this.agreeNum = agreeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_accept
     *
     * @return the value of comment.is_accept
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Integer getIsAccept() {
        return isAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_accept
     *
     * @param isAccept the value for comment.is_accept
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setIsAccept(Integer isAccept) {
        this.isAccept = isAccept;
    }
}