package com.bbgu.zmz.community.model;

import java.util.ArrayList;
import java.util.List;

public class KindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public KindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKindnameIsNull() {
            addCriterion("kindname is null");
            return (Criteria) this;
        }

        public Criteria andKindnameIsNotNull() {
            addCriterion("kindname is not null");
            return (Criteria) this;
        }

        public Criteria andKindnameEqualTo(String value) {
            addCriterion("kindname =", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameNotEqualTo(String value) {
            addCriterion("kindname <>", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameGreaterThan(String value) {
            addCriterion("kindname >", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameGreaterThanOrEqualTo(String value) {
            addCriterion("kindname >=", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameLessThan(String value) {
            addCriterion("kindname <", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameLessThanOrEqualTo(String value) {
            addCriterion("kindname <=", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameLike(String value) {
            addCriterion("kindname like", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameNotLike(String value) {
            addCriterion("kindname not like", value, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameIn(List<String> values) {
            addCriterion("kindname in", values, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameNotIn(List<String> values) {
            addCriterion("kindname not in", values, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameBetween(String value1, String value2) {
            addCriterion("kindname between", value1, value2, "kindname");
            return (Criteria) this;
        }

        public Criteria andKindnameNotBetween(String value1, String value2) {
            addCriterion("kindname not between", value1, value2, "kindname");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andKindCreateIsNull() {
            addCriterion("kind_create is null");
            return (Criteria) this;
        }

        public Criteria andKindCreateIsNotNull() {
            addCriterion("kind_create is not null");
            return (Criteria) this;
        }

        public Criteria andKindCreateEqualTo(Long value) {
            addCriterion("kind_create =", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateNotEqualTo(Long value) {
            addCriterion("kind_create <>", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateGreaterThan(Long value) {
            addCriterion("kind_create >", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("kind_create >=", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateLessThan(Long value) {
            addCriterion("kind_create <", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateLessThanOrEqualTo(Long value) {
            addCriterion("kind_create <=", value, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateIn(List<Long> values) {
            addCriterion("kind_create in", values, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateNotIn(List<Long> values) {
            addCriterion("kind_create not in", values, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateBetween(Long value1, Long value2) {
            addCriterion("kind_create between", value1, value2, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindCreateNotBetween(Long value1, Long value2) {
            addCriterion("kind_create not between", value1, value2, "kindCreate");
            return (Criteria) this;
        }

        public Criteria andKindModifiedIsNull() {
            addCriterion("kind_modified is null");
            return (Criteria) this;
        }

        public Criteria andKindModifiedIsNotNull() {
            addCriterion("kind_modified is not null");
            return (Criteria) this;
        }

        public Criteria andKindModifiedEqualTo(Long value) {
            addCriterion("kind_modified =", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedNotEqualTo(Long value) {
            addCriterion("kind_modified <>", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedGreaterThan(Long value) {
            addCriterion("kind_modified >", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("kind_modified >=", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedLessThan(Long value) {
            addCriterion("kind_modified <", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedLessThanOrEqualTo(Long value) {
            addCriterion("kind_modified <=", value, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedIn(List<Long> values) {
            addCriterion("kind_modified in", values, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedNotIn(List<Long> values) {
            addCriterion("kind_modified not in", values, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedBetween(Long value1, Long value2) {
            addCriterion("kind_modified between", value1, value2, "kindModified");
            return (Criteria) this;
        }

        public Criteria andKindModifiedNotBetween(Long value1, Long value2) {
            addCriterion("kind_modified not between", value1, value2, "kindModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}