package com.bbgu.zmz.community.model;

public class Kind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.kindname
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private String kindname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.category_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.kind_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long kindCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.kind_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    private Long kindModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.id
     *
     * @return the value of kind.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.id
     *
     * @param id the value for kind.id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.kindname
     *
     * @return the value of kind.kindname
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public String getKindname() {
        return kindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.kindname
     *
     * @param kindname the value for kind.kindname
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setKindname(String kindname) {
        this.kindname = kindname == null ? null : kindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.category_id
     *
     * @return the value of kind.category_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.category_id
     *
     * @param categoryId the value for kind.category_id
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.kind_create
     *
     * @return the value of kind.kind_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getKindCreate() {
        return kindCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.kind_create
     *
     * @param kindCreate the value for kind.kind_create
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setKindCreate(Long kindCreate) {
        this.kindCreate = kindCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.kind_modified
     *
     * @return the value of kind.kind_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public Long getKindModified() {
        return kindModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.kind_modified
     *
     * @param kindModified the value for kind.kind_modified
     *
     * @mbg.generated Tue Feb 04 17:00:00 GMT+08:00 2020
     */
    public void setKindModified(Long kindModified) {
        this.kindModified = kindModified;
    }
}