package com.bbgu.zmz.community.model;

public class Topicinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.title
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.topic_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long topicCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.topic_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long topicModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.category_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.kind_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long kindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.view_count
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.is_good
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Integer isGood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.is_end
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Integer isEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.is_top
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Integer isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.status
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.experience
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private Long experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicinfo.content
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.id
     *
     * @return the value of topicinfo.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.id
     *
     * @param id the value for topicinfo.id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.title
     *
     * @return the value of topicinfo.title
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.title
     *
     * @param title the value for topicinfo.title
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.topic_create
     *
     * @return the value of topicinfo.topic_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getTopicCreate() {
        return topicCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.topic_create
     *
     * @param topicCreate the value for topicinfo.topic_create
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setTopicCreate(Long topicCreate) {
        this.topicCreate = topicCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.topic_modified
     *
     * @return the value of topicinfo.topic_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getTopicModified() {
        return topicModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.topic_modified
     *
     * @param topicModified the value for topicinfo.topic_modified
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setTopicModified(Long topicModified) {
        this.topicModified = topicModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.user_id
     *
     * @return the value of topicinfo.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.user_id
     *
     * @param userId the value for topicinfo.user_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.category_id
     *
     * @return the value of topicinfo.category_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.category_id
     *
     * @param categoryId the value for topicinfo.category_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.kind_id
     *
     * @return the value of topicinfo.kind_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.kind_id
     *
     * @param kindId the value for topicinfo.kind_id
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setKindId(Long kindId) {
        this.kindId = kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.view_count
     *
     * @return the value of topicinfo.view_count
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.view_count
     *
     * @param viewCount the value for topicinfo.view_count
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.is_good
     *
     * @return the value of topicinfo.is_good
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Integer getIsGood() {
        return isGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.is_good
     *
     * @param isGood the value for topicinfo.is_good
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setIsGood(Integer isGood) {
        this.isGood = isGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.is_end
     *
     * @return the value of topicinfo.is_end
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.is_end
     *
     * @param isEnd the value for topicinfo.is_end
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.is_top
     *
     * @return the value of topicinfo.is_top
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.is_top
     *
     * @param isTop the value for topicinfo.is_top
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.status
     *
     * @return the value of topicinfo.status
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.status
     *
     * @param status the value for topicinfo.status
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.experience
     *
     * @return the value of topicinfo.experience
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public Long getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.experience
     *
     * @param experience the value for topicinfo.experience
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setExperience(Long experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicinfo.content
     *
     * @return the value of topicinfo.content
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicinfo.content
     *
     * @param content the value for topicinfo.content
     *
     * @mbg.generated Sun Dec 29 23:32:05 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}